version: "3"
services:
  web:
    build: .
    command: ["rerun", "--background", "--force-polling", "rails s -b 0.0.0.0"]
    volumes:
      - .:/app
    ports:
      - "3030:3030"
    depends_on:
      - db
      - redis
    environment:
      - WEBPACKER_DEV_SERVER_HOST=webpack
    env_file:
      - .env

  db:
    image: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"

  webpack:
    build: .
    command: bash -c "rm -rf ./public/packs; API_URL=${API_URL} ADMIN_ROLE_NAME=${ADMIN_ROLE_NAME} ./bin/webpack-dev-server"
    volumes:
      - .:/app
    ports:
      - "3035:3035"
    environment:
      - "NODE_ENV=development"
      - "RAILS_ENV=development"
      - "WEBPACKER_DEV_SERVER_HOST=0.0.0.0"
    env_file:
      - .env
  redis:
    image: "redis:5-alpine"
    command: redis-server
    ports:
      - "6380:6379"
    volumes:
      - "redis:/data"

volumes:
  pg_data:
  redis:
