version: '3'
services:
  web:
    build: .
    command: ["rerun", "--background", "--force-polling", "rails s -b 0.0.0.0"]
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - ADMIN_ROLE_NAME=${ADMIN_ROLE_NAME}
      - API_URL=${API_URL}
      - CONCEPTS_DIRECTORY_PATH=${CONCEPTS_DIRECTORY_PATH}
      - DEFAULT_PASS=${DEFAULT_PASS}
      - JWT_ALGORITHM=${JWT_ALGORITHM}
      - JWT_SECRET=${JWT_SECRET}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAILGUN_API_KEY=${MAILGUN_API_KEY}
      - MAILGUN_DOMAIN=${MAILGUN_DOMAIN}
      - MIN_PASSWORD_LENGTH=${MIN_PASSWORD_LENGTH}
      - WEBPACKER_DEV_SERVER_HOST=webpack

  db:
    image: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"

  webpack:
    build: .
    command: bash -c "rm -rf ./public/packs; API_URL=${API_URL} ADMIN_ROLE_NAME=${ADMIN_ROLE_NAME} ./bin/webpack-dev-server"
    volumes:
      - .:/app
    ports:
      - '3035:3035'
    environment:
      - "NODE_ENV=development"
      - "RAILS_ENV=development"
      - "WEBPACKER_DEV_SERVER_HOST=0.0.0.0"

volumes:
  pg_data:
    driver: local
