name: Linting
run-name: Linting workflow is launched by ${{ github.actor }} 🚀
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby for testing runner
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - run: yarn install --frozen-lockfile

      - name: Run overcommit tests
        run: |
          bundle exec overcommit --sign
          GIT_AUTHOR_EMAIL=ci@test.com GIT_AUTHOR_NAME='ci user' bundle exec overcommit --run

      - name: Checking Rails routes
        run: |
          if bundle exec rails traceroute 2>/dev/null | grep -qE '\([^0]\)'; then
            echo 'Unused routes or actions found!'
            exit 1
          fi
        continue-on-error: true

      - name: Run brakeman tests
        run: |
          bundle exec brakeman -zqA --summary --no-pager
        continue-on-error: true

